### ISSUE TITLE
add spacing for directory icon 

### ISSUE THREAD

**Issue by siduck** [AkinoKaede/Sarasa-Gothic-Term-SC-Nerd#2]
Sarasa term sc nerd font 

![image](https://user-images.githubusercontent.com/59060246/133197417-8d6c29f3-49fe-4e7f-b7c9-0935ba1bf221.png)

any other nerdfont I use 

![image](https://user-images.githubusercontent.com/59060246/133197488-6a5cca7a-996f-4991-85f8-3b2650043b44.png)

**Comment by siduck** [comment]
This is the icon 

![image](https://user-images.githubusercontent.com/59060246/133197541-254eeef3-b9f4-4c57-9369-632694b960e6.png)

**Comment by AkinoKaede** [comment]
I think is caused by I change the size of the icons to 1:2.

**Comment by siduck** [comment]
> I think is caused by I change the size of the icons to 1:2.

oh :<

**Comment by AkinoKaede** [comment]
Sorry, i remembered it wrong. I don't know the reason.
